project_id = "fwvlroxtuktcvvizncfa"

[functions.seed-demo]
verify_jwt = false

[functions.parse-command]
verify_jwt = false

[functions.form-assistant]
verify_jwt = false

[functions.setup-assistant]
verify_jwt = false

[functions.run-report]
verify_jwt = false

[functions.report-sql-assistant]
verify_jwt = false
